@startuml relation_schema
skinparam BackgroundColor transparent
skinparam componentStyle rectangle

component SDK
component ChatClient
component ChatManager
component ChatGroupManager
component ChatRoomManager
component ChatContactManager
component ChatUserInfoManager
component ChatPresenceManager

left to right direction

SDK --> ChatClient
SDK --> ChatManager
SDK --> ChatGroupManager
SDK --> ChatRoomManager
SDK --> ChatContactManager
SDK --> ChatUserInfoManager
SDK --> ChatPresenceManager

@enduml

' 这个是SDK核心组件。
' ChatClient是单实例对象，实现SDK初始化、参数配置、登录、退出等基本功能。
' ChatManager实现消息的发送、接收功能。
' ChatGroupManager实现群组的管理。包括创建群组、销毁群组、更新群组信息、管理成员等功能。
' ChatRoomManager实现聊天的管理。包括创建聊天室、更新信息、成员管理等功能。
' ChatContactManager实现通讯录的管理。包括添加好友、删除好友等功能。
' ChatUserInfoManager实现用户信息获取、更新当前用户信息的功能。
' ChatPresenceManager订阅用户状态管理。典型应用场景，例如：当前用户发布“我正在忙”的状态，订阅者将收到该状态。

' This is the core component of the SDK.
' ChatClient is a single-instance object that implements basic functions such as SDK initialization, parameter configuration, login, and logout.
' ChatManager implements message sending and receiving functions.
' ChatGroupManager implements group management. Including functions such as creating groups, destroying groups, updating group information, and managing members.
' ChatRoomManager implements chat management. Including functions such as creating chat rooms, updating information, and member management.
' ChatContactManager implements the management of the address book. Including adding friends, deleting friends and other functions.
' ChatUserInfoManager realizes the functions of obtaining user information and updating the current user information.
' ChatPresenceManager subscription user state management. Typical application scenarios, for example: the current user publishes the status "I am busy", and the subscribers will receive the status.
